[2022-02-28 14:19:19,319] INFO [GroupCoordinator 3]: Member consumer-groupId-01-7-0fa18a92-55f9-4193-8d19-3ee07034ca87 in group groupId-01 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 14:19:19,979] INFO [ReplicaFetcher replicaId=3, leaderId=1, fetcherId=0] Disconnecting from node 1 due to request timeout. (org.apache.kafka.clients.NetworkClient)
[2022-02-28 14:19:21,947] WARN Client session timed out, have not heard from server in 974828ms for session id 0x100b5f900320003 (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:21,453] INFO [GroupCoordinator 3]: Preparing to rebalance group groupId-01 in state PreparingRebalance with old generation 69 (__consumer_offsets-10) (reason: removing member consumer-groupId-01-7-0fa18a92-55f9-4193-8d19-3ee07034ca87 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 14:19:26,006] WARN Session 0x100b5f900320003 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 974828ms for session id 0x100b5f900320003
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258)
[2022-02-28 14:19:25,321] INFO [ReplicaFetcher replicaId=3, leaderId=1, fetcherId=0] Cancelled in-flight FETCH request with correlation id 109667 due to node 1 being disconnected (elapsed time since creation: 969486ms, elapsed time since send: 969486ms, request timeout: 30000ms) (org.apache.kafka.clients.NetworkClient)
[2022-02-28 14:19:26,511] INFO [GroupCoordinator 3]: Group groupId-01 with generation 70 is now empty (__consumer_offsets-10) (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 14:19:27,131] INFO [ReplicaFetcher replicaId=3, leaderId=1, fetcherId=0] Client requested connection close from node 1 (org.apache.kafka.clients.NetworkClient)
[2022-02-28 14:19:27,387] INFO [ReplicaFetcher replicaId=3, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=1898738782, epoch=28640) to node 1: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 1 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:99)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:109)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-28 14:19:28,308] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2182. (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:28,490] WARN [ReplicaFetcher replicaId=3, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=3, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={}, isolationLevel=READ_UNCOMMITTED, removed=, replaced=, metadata=(sessionId=1898738782, epoch=28640), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 1 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:99)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:109)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-28 14:19:28,607] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:28,838] INFO Socket connection established, initiating session, client: /0:0:0:0:0:0:0:1:51591, server: localhost/0:0:0:0:0:0:0:1:2182 (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:29,157] INFO [GroupCoordinator 3]: Dynamic member with unknown member id joins group groupId-01 in Empty state. Created a new member id consumer-groupId-01-7-0cef8217-d1bf-4e57-a3c5-6e592cb70425 and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 14:19:29,577] INFO [GroupCoordinator 3]: Preparing to rebalance group groupId-01 in state PreparingRebalance with old generation 70 (__consumer_offsets-10) (reason: Adding new member consumer-groupId-01-7-0cef8217-d1bf-4e57-a3c5-6e592cb70425 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 14:19:29,962] INFO [GroupCoordinator 3]: Stabilized group groupId-01 generation 71 (__consumer_offsets-10) with 1 members (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 14:19:30,024] INFO [GroupCoordinator 3]: Assignment received from leader consumer-groupId-01-7-0cef8217-d1bf-4e57-a3c5-6e592cb70425 for group groupId-01 for generation 71. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 14:19:30,136] WARN Unable to reconnect to ZooKeeper service, session 0x100b5f900320003 has expired (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:30,137] WARN Session 0x100b5f900320003 for sever localhost/0:0:0:0:0:0:0:1:2182, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionExpiredException: Unable to reconnect to ZooKeeper service, session 0x100b5f900320003 has expired
	at org.apache.zookeeper.ClientCnxn$SendThread.onConnected(ClientCnxn.java:1434)
	at org.apache.zookeeper.ClientCnxnSocket.readConnectResult(ClientCnxnSocket.java:154)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:86)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2022-02-28 14:19:30,143] INFO EventThread shut down for session: 0x100b5f900320003 (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:30,213] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2022-02-28 14:19:30,466] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181,localhost:2182,localhost:2183. (kafka.zookeeper.ZooKeeperClient)
[2022-02-28 14:19:30,490] INFO Initiating client connection, connectString=localhost:2181,localhost:2182,localhost:2183 sessionTimeout=18000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@7c7b252e (org.apache.zookeeper.ZooKeeper)
[2022-02-28 14:19:30,597] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[2022-02-28 14:19:30,629] INFO zookeeper.request.timeout value is 0. feature enabled=false (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:30,643] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2182. (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:30,644] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:30,645] INFO Socket connection established, initiating session, client: /0:0:0:0:0:0:0:1:51608, server: localhost/0:0:0:0:0:0:0:1:2182 (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:31,110] INFO Creating /brokers/ids/3 (is it secure? false) (kafka.zk.KafkaZkClient)
[2022-02-28 14:19:31,169] INFO Session establishment complete on server localhost/0:0:0:0:0:0:0:1:2182, session id = 0x200b5f9003c0009, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
[2022-02-28 14:19:31,273] INFO Updated cache from existing FinalizedFeaturesAndEpoch(features=Features{}, epoch=0) to latest FinalizedFeaturesAndEpoch(features=Features{}, epoch=0). (kafka.server.FinalizedFeatureCache)
[2022-02-28 14:19:31,304] INFO Stat of the created znode at /brokers/ids/3 is: 4294967720,4294967720,1646038171206,1646038171206,1,0,0,144315269131272201,202,0,4294967720
 (kafka.zk.KafkaZkClient)
[2022-02-28 14:19:31,308] INFO Registered broker 3 at path /brokers/ids/3 with addresses: PLAINTEXT://localhost:9094, czxid (broker epoch): 4294967720 (kafka.zk.KafkaZkClient)
