[2022-02-25 11:24:12,245] WARN Client session timed out, have not heard from server in 553122ms for session id 0x200b5f9003c0001 (org.apache.zookeeper.ClientCnxn)
[2022-02-25 11:24:12,315] WARN Session 0x200b5f9003c0001 for sever localhost/127.0.0.1:2182, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 553122ms for session id 0x200b5f9003c0001
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258)
[2022-02-25 11:24:12,953] INFO Opening socket connection to server localhost/127.0.0.1:2183. (org.apache.zookeeper.ClientCnxn)
[2022-02-25 11:24:13,135] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-25 11:24:13,168] INFO Socket connection established, initiating session, client: /127.0.0.1:50150, server: localhost/127.0.0.1:2183 (org.apache.zookeeper.ClientCnxn)
[2022-02-25 11:24:13,469] INFO EventThread shut down for session: 0x200b5f9003c0001 (org.apache.zookeeper.ClientCnxn)
[2022-02-25 11:24:13,473] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2022-02-25 11:24:13,469] WARN Unable to reconnect to ZooKeeper service, session 0x200b5f9003c0001 has expired (org.apache.zookeeper.ClientCnxn)
[2022-02-25 11:24:13,490] WARN Session 0x200b5f9003c0001 for sever localhost/127.0.0.1:2183, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionExpiredException: Unable to reconnect to ZooKeeper service, session 0x200b5f9003c0001 has expired
	at org.apache.zookeeper.ClientCnxn$SendThread.onConnected(ClientCnxn.java:1434)
	at org.apache.zookeeper.ClientCnxnSocket.readConnectResult(ClientCnxnSocket.java:154)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:86)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2022-02-25 11:24:13,512] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181,localhost:2182,localhost:2183. (kafka.zookeeper.ZooKeeperClient)
[2022-02-25 11:24:13,514] INFO Initiating client connection, connectString=localhost:2181,localhost:2182,localhost:2183 sessionTimeout=18000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@459e9125 (org.apache.zookeeper.ZooKeeper)
[2022-02-25 11:24:13,544] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[2022-02-25 11:24:13,549] INFO zookeeper.request.timeout value is 0. feature enabled=false (org.apache.zookeeper.ClientCnxn)
[2022-02-25 11:24:13,562] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2182. (org.apache.zookeeper.ClientCnxn)
[2022-02-25 11:24:13,562] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-25 11:24:13,563] INFO Socket connection established, initiating session, client: /0:0:0:0:0:0:0:1:50153, server: localhost/0:0:0:0:0:0:0:1:2182 (org.apache.zookeeper.ClientCnxn)
[2022-02-25 11:24:13,608] INFO Session establishment complete on server localhost/0:0:0:0:0:0:0:1:2182, session id = 0x200b5f9003c0003, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
[2022-02-25 11:24:13,665] INFO Creating /brokers/ids/1 (is it secure? false) (kafka.zk.KafkaZkClient)
[2022-02-25 11:24:13,718] INFO Stat of the created znode at /brokers/ids/1 is: 4294967499,4294967499,1645768453671,1645768453671,1,0,0,144315269131272195,202,0,4294967499
 (kafka.zk.KafkaZkClient)
[2022-02-25 11:24:13,723] INFO Registered broker 1 at path /brokers/ids/1 with addresses: PLAINTEXT://localhost:9092, czxid (broker epoch): 4294967499 (kafka.zk.KafkaZkClient)
[2022-02-25 11:24:13,741] INFO Updated cache from existing FinalizedFeaturesAndEpoch(features=Features{}, epoch=0) to latest FinalizedFeaturesAndEpoch(features=Features{}, epoch=0). (kafka.server.FinalizedFeatureCache)
[2022-02-25 11:24:14,685] INFO [ReplicaFetcherManager on broker 1] Removed fetcher for partitions Set(topic02-1) (kafka.server.ReplicaFetcherManager)
[2022-02-25 11:24:14,959] INFO [ReplicaFetcherManager on broker 1] Removed fetcher for partitions Set(topic02-0, topic02-2) (kafka.server.ReplicaFetcherManager)
[2022-02-25 11:24:15,010] INFO [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Shutting down (kafka.server.ReplicaFetcherThread)
[2022-02-25 11:24:15,012] INFO [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Client requested connection close from node 2 (org.apache.kafka.clients.NetworkClient)
[2022-02-25 11:24:15,013] INFO [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Cancelled in-flight FETCH request with correlation id 28120 due to node 2 being disconnected (elapsed time since creation: 395ms, elapsed time since send: 395ms, request timeout: 30000ms) (org.apache.kafka.clients.NetworkClient)
[2022-02-25 11:24:15,013] INFO [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Error sending fetch request (sessionId=122568050, epoch=17450) to node 2: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Client was shutdown before response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:108)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:109)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-25 11:24:15,015] INFO [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Stopped (kafka.server.ReplicaFetcherThread)
[2022-02-25 11:24:15,015] INFO [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Shutdown completed (kafka.server.ReplicaFetcherThread)
[2022-02-25 11:24:15,039] INFO [ReplicaFetcher replicaId=1, leaderId=3, fetcherId=0] Shutting down (kafka.server.ReplicaFetcherThread)
[2022-02-25 11:24:15,043] INFO [ReplicaFetcher replicaId=1, leaderId=3, fetcherId=0] Client requested connection close from node 3 (org.apache.kafka.clients.NetworkClient)
[2022-02-25 11:24:15,044] INFO [ReplicaFetcher replicaId=1, leaderId=3, fetcherId=0] Cancelled in-flight FETCH request with correlation id 28359 due to node 3 being disconnected (elapsed time since creation: 393ms, elapsed time since send: 393ms, request timeout: 30000ms) (org.apache.kafka.clients.NetworkClient)
[2022-02-25 11:24:15,047] INFO [ReplicaFetcher replicaId=1, leaderId=3, fetcherId=0] Error sending fetch request (sessionId=368837918, epoch=17686) to node 3: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Client was shutdown before response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:108)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:109)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-25 11:24:15,048] INFO [ReplicaFetcher replicaId=1, leaderId=3, fetcherId=0] Stopped (kafka.server.ReplicaFetcherThread)
[2022-02-25 11:24:15,048] INFO [ReplicaFetcher replicaId=1, leaderId=3, fetcherId=0] Shutdown completed (kafka.server.ReplicaFetcherThread)
[2022-02-25 11:24:15,542] INFO [Partition topic02-2 broker=1] ISR updated to 1,2 and version updated to 4 (kafka.cluster.Partition)
[2022-02-25 11:24:15,574] INFO [Partition topic02-1 broker=1] ISR updated to 1,3 and version updated to 3 (kafka.cluster.Partition)
[2022-02-25 11:24:15,575] INFO [Partition topic02-0 broker=1] ISR updated to 1,3 and version updated to 4 (kafka.cluster.Partition)
[2022-02-25 11:24:16,024] INFO [Partition topic02-2 broker=1] ISR updated to 1,2,3 and version updated to 5 (kafka.cluster.Partition)
[2022-02-25 11:24:16,050] INFO [Partition topic02-1 broker=1] ISR updated to 1,3,2 and version updated to 4 (kafka.cluster.Partition)
[2022-02-25 11:24:16,051] INFO [Partition topic02-0 broker=1] ISR updated to 1,3,2 and version updated to 5 (kafka.cluster.Partition)
[2022-02-25 11:34:16,098] INFO [BrokerToControllerChannelManager broker=1 name=alterIsr] Node 1 disconnected. (org.apache.kafka.clients.NetworkClient)
