[2022-02-28 10:31:06,073] INFO [GroupCoordinator 2]: Member console-consumer-9ddfc5b5-75aa-4160-bc40-885cb2dd72a8 in group console-consumer-12642 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 10:31:06,132] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Node 1 disconnected. (org.apache.kafka.clients.NetworkClient)
[2022-02-28 10:31:06,482] WARN Session 0x300b5f942b40006 for sever localhost/127.0.0.1:2183, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
EndOfStreamException: Unable to read additional data from server sessionid 0x300b5f942b40006, likely server has closed socket
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2022-02-28 10:31:06,517] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Cancelled in-flight FETCH request with correlation id 84629 due to node 1 being disconnected (elapsed time since creation: 53875301ms, elapsed time since send: 53875301ms, request timeout: 30000ms) (org.apache.kafka.clients.NetworkClient)
[2022-02-28 10:31:06,512] INFO [GroupCoordinator 2]: Preparing to rebalance group console-consumer-12642 in state PreparingRebalance with old generation 3 (__consumer_offsets-36) (reason: removing member console-consumer-9ddfc5b5-75aa-4160-bc40-885cb2dd72a8 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 10:31:06,546] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Client requested connection close from node 1 (org.apache.kafka.clients.NetworkClient)
[2022-02-28 10:31:06,556] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=1445751523, epoch=3584) to node 1: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 1 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:99)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:109)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-28 10:31:06,560] INFO [GroupCoordinator 2]: Group console-consumer-12642 with generation 4 is now empty (__consumer_offsets-36) (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 10:31:06,878] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={}, isolationLevel=READ_UNCOMMITTED, removed=, replaced=, metadata=(sessionId=1445751523, epoch=3584), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 1 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:99)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:109)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-28 10:31:07,227] INFO [GroupCoordinator 2]: Dynamic member with unknown member id joins group console-consumer-12642 in Empty state. Created a new member id console-consumer-b8d5b9bc-3059-496e-a9ec-ca42ec35c165 and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 10:31:07,279] INFO [GroupCoordinator 2]: Preparing to rebalance group console-consumer-12642 in state PreparingRebalance with old generation 4 (__consumer_offsets-36) (reason: Adding new member console-consumer-b8d5b9bc-3059-496e-a9ec-ca42ec35c165 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 10:31:07,307] INFO [GroupCoordinator 2]: Stabilized group console-consumer-12642 generation 5 (__consumer_offsets-36) with 1 members (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 10:31:07,326] INFO [GroupCoordinator 2]: Assignment received from leader console-consumer-b8d5b9bc-3059-496e-a9ec-ca42ec35c165 for group console-consumer-12642 for generation 5. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 10:31:07,372] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. (org.apache.zookeeper.ClientCnxn)
[2022-02-28 10:31:07,372] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-28 10:31:07,384] INFO Socket connection established, initiating session, client: /0:0:0:0:0:0:0:1:64808, server: localhost/0:0:0:0:0:0:0:1:2181 (org.apache.zookeeper.ClientCnxn)
[2022-02-28 10:31:07,536] INFO EventThread shut down for session: 0x300b5f942b40006 (org.apache.zookeeper.ClientCnxn)
[2022-02-28 10:31:07,539] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2022-02-28 10:31:07,575] WARN Unable to reconnect to ZooKeeper service, session 0x300b5f942b40006 has expired (org.apache.zookeeper.ClientCnxn)
[2022-02-28 10:31:07,576] WARN Session 0x300b5f942b40006 for sever localhost/0:0:0:0:0:0:0:1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionExpiredException: Unable to reconnect to ZooKeeper service, session 0x300b5f942b40006 has expired
	at org.apache.zookeeper.ClientCnxn$SendThread.onConnected(ClientCnxn.java:1434)
	at org.apache.zookeeper.ClientCnxnSocket.readConnectResult(ClientCnxnSocket.java:154)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:86)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2022-02-28 10:31:07,590] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181,localhost:2182,localhost:2183. (kafka.zookeeper.ZooKeeperClient)
[2022-02-28 10:31:07,593] INFO Initiating client connection, connectString=localhost:2181,localhost:2182,localhost:2183 sessionTimeout=18000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@7c7b252e (org.apache.zookeeper.ZooKeeper)
[2022-02-28 10:31:07,648] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[2022-02-28 10:31:07,677] INFO zookeeper.request.timeout value is 0. feature enabled=false (org.apache.zookeeper.ClientCnxn)
[2022-02-28 10:31:07,701] INFO Opening socket connection to server localhost/127.0.0.1:2183. (org.apache.zookeeper.ClientCnxn)
[2022-02-28 10:31:07,701] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-28 10:31:07,702] INFO Socket connection established, initiating session, client: /127.0.0.1:64815, server: localhost/127.0.0.1:2183 (org.apache.zookeeper.ClientCnxn)
[2022-02-28 10:31:07,808] INFO Session establishment complete on server localhost/127.0.0.1:2183, session id = 0x300b5f942b40008, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
[2022-02-28 10:31:07,855] INFO Creating /brokers/ids/2 (is it secure? false) (kafka.zk.KafkaZkClient)
[2022-02-28 10:31:07,930] INFO Stat of the created znode at /brokers/ids/2 is: 4294967712,4294967712,1646024467890,1646024467890,1,0,0,216372864284360712,202,0,4294967712
 (kafka.zk.KafkaZkClient)
[2022-02-28 10:31:07,936] INFO Registered broker 2 at path /brokers/ids/2 with addresses: PLAINTEXT://localhost:9093, czxid (broker epoch): 4294967712 (kafka.zk.KafkaZkClient)
[2022-02-28 10:31:07,977] INFO Updated cache from existing FinalizedFeaturesAndEpoch(features=Features{}, epoch=0) to latest FinalizedFeaturesAndEpoch(features=Features{}, epoch=0). (kafka.server.FinalizedFeatureCache)
[2022-02-28 10:32:16,281] INFO [GroupCoordinator 2]: Dynamic member with unknown member id joins group console-consumer-69689 in Empty state. Created a new member id console-consumer-cdfa1b43-afef-4201-8a22-59d109c687c0 and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 10:32:16,287] INFO [GroupCoordinator 2]: Preparing to rebalance group console-consumer-69689 in state PreparingRebalance with old generation 0 (__consumer_offsets-9) (reason: Adding new member console-consumer-cdfa1b43-afef-4201-8a22-59d109c687c0 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 10:32:16,290] INFO [GroupCoordinator 2]: Stabilized group console-consumer-69689 generation 1 (__consumer_offsets-9) with 1 members (kafka.coordinator.group.GroupCoordinator)
[2022-02-28 10:32:16,297] INFO [GroupCoordinator 2]: Assignment received from leader console-consumer-cdfa1b43-afef-4201-8a22-59d109c687c0 for group console-consumer-69689 for generation 1. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
